name: MLflow_CI_Skilled

on:
  push:
    branches: [ main ]

jobs:
  mlflow_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MLflow
        run: pip install mlflow pandas scikit-learn

      - name: Run MLflow Project
        working-directory: ./MLProject
        run: mlflow run . --no-conda 

      - name: Push Artifacts to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add retrained model artifacts [Skilled]" && git push)
